export { default as Navbar } from "./Navbar"
export { default as Hero } from "./Hero"
export { default as Loader } from "./Loader"
export { default as Team } from "./Team"
export { default as ScrollDown } from "./ScrollDown"
export { default as Roadmap } from "./Roadmap"
export { default as Solution } from "./Solution"
export { default as Pricing } from "./Pricing"
